#!/bin/bash

data-gen/target/debug/data-gen file:timedata_1.json 0:00 1:00 9:00 10:00 13:00 13:45
if [ $? -ne 0 ]
then
  echo "Upload failed"
  exit 1
fi

curl --data-binary "@timedata_1.json" -H 'Content-Type: application/json' http://192.168.1.177/CH/schedule

data-gen/target/debug/data-gen file:timedata_2.json 1:30 1:45 
if [ $? -ne 0 ]
then
  echo "Upload failed"
  exit 1
fi

curl --data-binary "@timedata_2.json" -H 'Content-Type: application/json' http://192.168.1.177/HW/schedule
