[package]
name = "data-gen"
version = "0.1.0"
authors = ["stuartdd <stuart.d.davies@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
